export const manufacturers = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const yearsOfProduction = [
  { title: "Year", value: "" },
  { title: "2015", value: "2015" },
  { title: "2016", value: "2016" },
  { title: "2017", value: "2017" },
  { title: "2018", value: "2018" },
  { title: "2019", value: "2019" },
  { title: "2020", value: "2020" },
  { title: "2021", value: "2021" },
  { title: "2022", value: "2022" },
  { title: "2023", value: "2023" },
];

export const fuels = [
  {
    title: "Fuel",
    value: "",
  },
  {
    title: "Gas",
    value: "Gas",
  },
  {
    title: "Electricity",
    value: "Electricity",
  },
];

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Bussiness Relation", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];

// export const price [
//   { title: "Acura", value: "150" },
//   { title: "Alfa Romeo", value: "180" },
//   { title: "Aston Martin", value: "1500" },
//   { title: "Audi", value: "200" },
//   { title: "Bentley", value: "1800" },
//   { title: "BMW", value: "190" },
//   { title: "Buick", value: "100" },
//   { title: "Cadillac", value: "140" },
//   { title: "Chevrolet", value: "90" },
//   { title: "Chrysler", value: "95" },
//   { title: "Citroen", value: "110" },
//   { title: "Dodge", value: "100" },
//   { title: "Ferrari", value: "1900" },
//   { title: "Fiat", value: "85" },
//   { title: "Ford", value: "95" },
//   { title: "GMC", value: "110" },
//   { title: "Honda", value: "85" },
//   { title: "Hyundai", value: "80" },
//   { title: "Infiniti", value: "120" },
//   { title: "Jaguar", value: "170" },
//   { title: "Jeep", value: "110" },
//   { title: "Kia", value: "80" },
//   { title: "Lamborghini", value: "1800" },
//   { title: "Land Rover", value: "160" },
//   { title: "Lexus", value: "140" },
//   { title: "Lincoln", value: "130" },
//   { title: "Maserati", value: "1600" },
//   { title: "Mazda", value: "85" },
//   { title: "McLaren", value: "1700" },
//   { title: "Mercedes-Benz", value: "180" },
//   { title: "MINI", value: "95" },
//   { title: "Mitsubishi", value: "80" },
//   { title: "Nissan", value: "90" },
//   { title: "Porsche", value: "200" },
//   { title: "Ram", value: "110" },
//   { title: "Rolls-Royce", value: "2000" },
//   { title: "Subaru", value: "85" },
//   { title: "Tesla", value: "170" },
//   { title: "Toyota", value: "90" },
//   { title: "Volkswagen", value: "95" },
//   { title: "Volvo", value: "130" }
// ];
